source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'tw10n_Example', :exclusive => true do
  pod "tw10n", :path => "../"
end

target 'tw10n_Tests', :exclusive => true do
  pod "tw10n", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
